micronaut:
  application:
    name: dbRepositories
endpoints:
  routes:
    enabled: true
    sensitive: false
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/airbyte
    username: docker
    password: docker
    driverClassName: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
        - "io.airbyte.db.repositories"
        - "io.airbyte.db.repositories.models"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
