connector_image: airbyte/source-amplitude:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_amplitude/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.txt"
        empty_streams:
          - name: "events"
            bypass_reason: "The stream is too large and frequently changing, due to test with live account."
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog_without_events.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog_without_events.json"
