[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "4.3.0"
name = "source-tiktok-marketing"
description = "Source implementation for Tiktok Marketing."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/tiktok-marketing"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_tiktok_marketing"

[tool.poetry.dependencies]
python = "^3.10"
airbyte-cdk = "^4"

[tool.poetry.scripts]
source-tiktok-marketing = "source_tiktok_marketing.run:run"

[tool.poetry.group.dev.dependencies]
requests-mock = "*"
timeout-decorator = "==0.5.0"
pytest-mock = "*"
pytest = "*"
