[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "1.3.0"
name = "source-snapchat-marketing"
description = "Source implementation for Snapchat Marketing."
authors = [ "Airbyte <contact@airbyte.io>",]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/snapchat-marketing"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_snapchat_marketing"

[tool.poetry.dependencies]
python = "^3.10"
airbyte-cdk = "^4"

[tool.poetry.scripts]
source-snapchat-marketing = "source_snapchat_marketing.run:run"

[tool.poetry.group.dev.dependencies]
pytest-mock = "*"
pytest = "*"
requests-mock = "*"
